repos:
  - repo: local
    hooks:
      - id: isort
        name:  isort
        entry: poetry run isort --check .
        language: system
        types:
          - python

      - id: black
        name: black
        entry: poetry run black --check .
        language: system
        types:
          - python
